//
// Created by Lenovo on 17.10.2024.
//

#ifndef OPTIMISATION_OF_TSP_PROJECT1_BRUTEFORCEALGORITHM_H
#define OPTIMISATION_OF_TSP_PROJECT1_BRUTEFORCEALGORITHM_H


class BruteForceAlgorithm {

};


#endif //OPTIMISATION_OF_TSP_PROJECT1_BRUTEFORCEALGORITHM_H
