//
// Created by Lenovo on 17.10.2024.
//

#ifndef OPTIMISATION_OF_TSP_PROJECT1_NEARESTNEIGHBORALGORITHM_H
#define OPTIMISATION_OF_TSP_PROJECT1_NEARESTNEIGHBORALGORITHM_H


class NearestNeighborAlgorithm {

};


#endif //OPTIMISATION_OF_TSP_PROJECT1_NEARESTNEIGHBORALGORITHM_H
